config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    resources :works do
      resources :tasks
    end

    resources :pages
    resources :prospects
    # Defines the root path route ("/")
    root "pages#home"
    get "about", to: "pages#about"
    get "works", to: "works#index"
    get "kraze", to: "works#kraze"
    get "lcl", to: "works#lcl"
    get "cryptopassion", to: "works#cryptopassion"
    get "accor", to: "works#accor"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/prospect.rb
class Prospect < ApplicationRecord
  belongs_to :work
end

app/models/task.rb
class Task < ApplicationRecord
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  has_one_attached :photo

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private

  def default_url_options
    {locale: I18n.locale}
  end

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end

  def extract_locale
    parsed_locale = params[:locale]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ?
      parsed_locale.to_sym :
      nil
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about, :index, :works], raise: false
  def index

  end
  def home

  end
  def about

  end
  def works

  end
  def kraze

  end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  def index
    @prospects = Prospect.all
  end
  def new
    @prospects = Prospect.new
  end
  def create
    @prospects = Prospect.new(prospect_params)
    @prospects.save
  end

  private

  def prospect_params
    params.require(:prospect).permit(:email)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_works
  def index
    @task = Task.all
  end

  def new
    @task = @work.tasks.build
  end

  def create
    @task = @work.tasks.build(task_params)
    @task.save
    redirect_to work_path
  end

  private

  def set_works
    @work = Work.find(params[:work_id])
  end

  def task_params
    params.require(:task).permit(:name, :description)
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController

  # before_action :authenticate_user!, except: [:index, :show]

  #def index
  #  @works = Work.all
  #end
#
  #def show
  #  @work = Work.find(params[:id])
  #end

  #def new
  #  @work = Work.new
  #end
#
  #def create
  #  @work = Work.new(work_params)
  #  @work.save
  #  redirect_to work_path(@work)
  #end

  #def edit
  #  @work = Work.find(params[:id])
  #end

  #def update
  #  @work = Work.find(params[:id])
  #  @work.update(work_params)
  #  redirect_to work_path(@work)
  #end

  #def destroy
  #  @work = Work.find(params[:id])
  #  @work.destroy
  #  redirect_to works_path, status: :see_other
  #end

  def tasks
  end

  def accor
  end

  def kraze
  end

  def lcl
  end

  def cryptopassion
  end

  # Static pages

  private

  def work_params
    params.require(:work).permit(:name, :description, :photo, :tasks)
  end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/pages/home.html.erb
<div class="banner">
  <div class="row title d-flex">
    <div class="col-md-7 col-sm-12 align-self-center claim">
      <h1 class="heading-01 mb-4 ">Product<br>UX/UI<br> Designer</h1>
      <p class="sub-heading-03 mb-5" ><%= t 'pages.home.services' %></p>
      <a href="" class="button-accent" onclick= "Calendly.initPopupWidget({url:'https://calendly.com/ant-pecheux/15min'}) ;return false;"><%= t "pages.home.adopt" %></a>
    </div>
  </div>
</div>

<%= render "shared/selected-works" %>
<%= render "shared/advantages-block" %>
<%= render "shared/instagram-block" %>
<%= render "shared/testimonials" %>

app/views/shared/_advantages-block.html.erb
<div class="advantages-block">
  <div class="container">
    <div class="row">
      <h2 class="col-md-3 col-sm-12"><%= t "partials.advantages.title" %></h2>
      <div class="col-md-3 col-sm-12 d-flex">
        <p class="advantages-block-number">1.</p>
        <div class="pt-4">
          <h3><%= t "partials.advantages.advantage1-title" %></h3>
          <p class="ui-regular-01"><%= t "partials.advantages.advantage1-description" %></p>
        </div>
      </div>
      <div class="col-md-3 col-sm-12 d-flex">
        <p class="advantages-block-number">2.</p>
        <div class="pt-4">
          <h3><%= t "partials.advantages.advantage2-title" %></h3>
          <p class="ui-regular-01"><%= t "partials.advantages.advantage2-description" %></p>
        </div>
      </div>
      <div class="col-md-3 col-sm-12 d-flex">
        <p class="advantages-block-number">3.</p>
        <div class="pt-4">
          <h3><%= t "partials.advantages.advantage3-title" %></h3>
          <p class="ui-regular-01"><%= t "partials.advantages.advantage2-description" %></p>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-center mt-03">
      <%= link_to t("partials.advantages.button"), about_path , class: "button-primary text-center button-advantage" %>
    </div>
  </div>
</div>

app/views/shared/_back-button.html.erb
<a href="<%= root_path %>" style="text-decoration: none" class="button-back">
  <p class="ui-regular-01" style="margin-bottom: 0px"><i class="fa-sharp fa-solid fa-arrow-left"></i><%= t "nav.back-button" %></p>
</a>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-12">
        <h3 class="sub-heading-03"><%= t "partials.footer.services" %></h3>
        <ul>
          <li class="">
            <%= link_to t("partials.footer.home"), root_path , class: "" %>
          </li>
          <li class="">
            <%= link_to t("partials.footer.works"), works_path , class: "" %>
          </li>
          <li class="">
            <%= link_to t("partials.footer.about"), about_path , class: "" %>
          </li>
          <li class="ui-regular-01 mt-3" style="opacity: 0.6">
            © Peachux 2022
          </li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-12">
        <h3 class="sub-heading-03"><%= t "partials.footer.follow" %></h3>
        <ul>
          <li class="">
            <a href="https://www.linkedin.com/in/antoine-p%C3%AAcheux-22541182/" target="_blank">LinkedIn</a>
          </li>
          <li class="">
            <a href="https://www.instagram.com/peach.ux/" target="_blank">Instagram</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="madewith">
  <div class="container text-center">
    <p class="ui-bold-01 align-items-start pt-3">🍑 Designed by your bro AE 🍑</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-peachux fixed-top">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("https://res.cloudinary.com/peachux/image/upload/v1667396587/website/logo-full.png") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "About", about_path , class: "nav-link" %>
          </li>
          <li class="nav-item align-self-center">
            <a href="" class="button-accent" onclick= "Calendly.initPopupWidget({url:'https://calendly.com/ant-pecheux/15min'}) ;return false;">Make an appointment</a>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, class: "nav-link", style:"color:#E11E6A", data: {turbo_method: :delete} %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t("nav.about"), about_path , class: "nav-link" %>
          </li>
          <li class="nav-item">
            <div class="dropdown">
              <button class="button-language dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= t "nav.language" %>
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to '🇬🇧 English', url_for( :locale => 'en' ), class: "nav-link nav-item "%>
                <%= link_to '🇫🇷 Français', url_for( :locale => 'fr' ), class: "nav-link nav-item "%>
              </div>
            </div>
          </li>
          <li class="nav-item align-self-center button-calendly-nav">
            <button class="button-accent">
              <a href="" style="text-decoration: none; color: white;" onclick= "Calendly.initPopupWidget({url:'https://calendly.com/ant-pecheux/15min'}) ;return false;"><%= t "nav.appointment" %></a>
            </button>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_selected-works.html.erb
<div class="selected-works works">
  <div class="container">
    <h2 class="justify-content-center sub-heading-02"><%= t "pages.works.title" %></h2>
    <div class="row justify-content-center">
      <a href="<%= accor_path %>" class="col-md-4 col-sm-12 work-card d-flex align-items-end p-4" style="background-image: url(https://res.cloudinary.com/peachux/image/upload/v1669124778/website/Accor_cover.jpg)">
        <h3 class="work-card-link">Accor</h3>
      </a>
      <a href="<%= kraze_path %>" class="col-md-4 col-sm-12 work-card d-flex align-items-end p-4" style="background-image: url(https://res.cloudinary.com/peachux/image/upload/v1669124771/website/Kraze_cover.jpg)">
        <h3 class="work-card-link">Kraze</h3>
      </a>
      <a href="<%= lcl_path %>" class="col-md-4 col-sm-12 work-card d-flex align-items-end p-4" style="background-image: url(https://res.cloudinary.com/peachux/image/upload/v1669124803/website/Lcl_cover.jpg)">
        <h3 class="work-card-link">LCL</h3>
      </a>
      <a href="<%= cryptopassion_path %>" class="col-md-4 col-sm-12 work-card d-flex align-items-end p-4" style="background-image: url(https://res.cloudinary.com/peachux/image/upload/v1669124787/website/CP_cover.jpg)">
        <h3 class="work-card-link">CryptoPassion</h3>
      </a>
    </div>
  </div>
</div>

app/views/works/accor.html.erb
<!-- WORK HEADER -->

<div class="container">

  <%= render "shared/back-button" %>

  <div class="work-header d-flex">
    <div class="row align-self-stretch">
      <div class="col-md-7 col-sm-12 offset-md-0">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124778/website/Accor_cover.jpg" alt="Accor cover" class="work-header-image">
      </div>
      <div class="col-md-5 col-sm-12 work-header-content d-flex align-content-end flex-wrap offset-md-0 ps-4" >
        <h1 class="heading-02">Accor</h1>
        <p class="ui-regular-01"><%= t "pages.accor.description" %></p>
      </div>
    </div>
  </div>

  <!-- Tasks -->

  <div class="work-block">
    <div class="row justify-content-center">
      <div class="col-md-4 col-sm-12">
        <h2 class="sub-heading-03 mb-3"><%= t "pages.accor.task-title" %></h2>
        <p class="ui-regular-01"><%= t "pages.accor.task-description1" %></p>
        <p class="ui-regular-01"><%= t "pages.accor.task-description2" %></p>
        <p class="ui-regular-01"><%= t "pages.accor.task-description3" %></p>
        <p class="ui-regular-01"><%= t "pages.accor.task-description4" %></p>
        <p class="ui-regular-01"><%= t "pages.accor.task-description5" %></p>
      </div>
      <div class="col-md-4 col-sm-12">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124778/website/Accor_goals.jpg" alt="Accor goals" class="works-img">
        <p class="ui-regular-03 caption pt-2"><%= t "pages.accor.task-img-caption" %></p>
      </div>
    </div>
  </div>

  <!-- INFORMATION ARCHITECTURE -->

  <div class="work-block">
    <div class="row justify-content-center">
      <div class="col-md-4 col-sm-12">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124780/website/Accor_backlog.jpg" alt="Accor backlog" class="works-img">
        <p class="ui-regular-03 caption pt-2"><%= t "pages.accor.backlog-img-caption" %></p>
      </div>
      <div class="col-md-4 col-sm-12">
        <h2 class="sub-heading-03 mb-3"><%= t "pages.accor.backlog-title" %></h2>
        <p class="ui-regular-01"><%= t "pages.accor.backlog-description" %></p>
      </div>
    </div>
  </div>
</div>

<!-- FOCUS -->

<div class="focus">
  <div class="container">
    <h2 class="sub-heading-03 text-center my-4"><%= t "pages.accor.focus-title" %></h2>
    <div class="row justify-content-center">
      <div class="col-md-4 col-sm-12">
        <p class="ui-regular-01 mt-3" style="color: white; text-align: center;"><%= t "pages.accor.focus-description" %></p>
      </div>
    </div>
  </div>
</div>

<!-- Design system and library -->

<div class="container">
  <div class="work-block">
    <div class="row justify-content-center">
      <div class="col-md-4 col-sm-12">
        <h2 class="sub-heading-03 mb-3"><%= t "pages.accor.data-title" %></h2>
        <p class="ui-regular-01"><%= t "pages.accor.data-description" %></p>
      </div>
      <div class="col-md-4 col-sm-12">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124777/website/Accor_data.jpg" alt="Kraze DS" class="works-img">
        <p class="ui-regular-03 caption pt-2"><%= t "pages.accor.data-img-caption" %></p>
      </div>
    </div>
  </div>
</div>

<!-- Next project -->

<div class="next-work">
  <div class="container">
    <div class="d-md-flex justify-content-between mb-4">
      <h2 class="sub-heading-02 mb-3"><%= t "pages.works.next-work" %></h2>
    </div>

    <a href="<%= kraze_path %>" style="text-decoration: none">
      <div class="next-work-section" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url(https://res.cloudinary.com/peachux/image/upload/v1669718503/website/Kraze_next.png);">
        Kraze
      </div>
    </a>
  </div>
</div>

<%= render "shared/advantages-block" %>

app/views/works/cryptopassion.html.erb
<!-- WORK HEADER -->

<div class="container">

  <%= render "shared/back-button" %>

  <div class="work-header d-flex">
    <div class="row align-self-stretch">
      <div class="col-md-7 col-sm-12 offset-md-0">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124787/website/CP_cover.jpg" alt="LCL cover" class="work-header-image">
      </div>
      <div class="col-md-5 col-sm-12 work-header-content d-flex align-content-end flex-wrap offset-md-0 ps-4" >
        <h1 class="heading-02">Crypto<br>Passion</h1>
        <p class="ui-regular-01"><%= t "pages.cryptopassion.description" %></p>
      </div>
    </div>
  </div>

<!-- Tasks -->

  <div class="work-block">
    <div class="row justify-content-center">
      <div class="col-md-4 col-sm-12">
        <h2 class="sub-heading-03 mb-3"><%= t "pages.cryptopassion.goals-title" %></h2>
        <p class="ui-regular-01"><%= t "pages.cryptopassion.goals-description" %></p>
      </div>
      <div class="col-md-4 col-sm-12">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124789/website/CP_goals.jpg" alt="CryptoPassion goals" class="works-img">
        <p class="ui-regular-03 caption pt-2"><%= t "pages.cryptopassion.goals-img-caption" %></p>
      </div>
    </div>
  </div>

<!-- Quantitative studies -->

  <div class="work-block">
    <div class="row justify-content-center">
      <div class="col-md-4 col-sm-12">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124787/website/CP_quantitative.png" alt="CryptoPassion quanti" class="works-img">
        <p class="ui-regular-03 caption pt-2"><%= t "pages.cryptopassion.quantitative-img-caption" %></p>
      </div>
      <div class="col-md-4 col-sm-12">
        <h2 class="sub-heading-03 mb-3"><%= t "pages.cryptopassion.quantitative-title" %></h2>
        <p class="ui-regular-01"><%= t "pages.cryptopassion.quantitative-description" %></p>
      </div>
    </div>
  </div>
</div>

<!-- Qualitative studies -->

<div class="container">
  <div class="work-block">
    <div class="row justify-content-center">
      <div class="col-md-4 col-sm-12">
        <h2 class="sub-heading-03 mb-3"><%= t "pages.cryptopassion.qualitative-title" %></h2>
        <p class="ui-regular-01"><%= t "pages.cryptopassion.qualitative-description" %></p>
      </div>
      <div class="col-md-4 col-sm-12">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124788/website/CP_qualitative.jpg" alt="CryptoPassion quali" class="works-img">
        <p class="ui-regular-03 caption pt-2"><%= t "pages.cryptopassion.qualitative-img-caption" %></p>
      </div>
    </div>
  </div>

<!-- Storytelling -->

  <div class="work-block">
    <div class="row justify-content-center">
      <div class="col-md-4 col-sm-12">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124787/website/CP_logo.png" alt="Kraze info archi 1" class="works-img">
        <p class="ui-regular-03 caption pt-2"><%= t "pages.cryptopassion.storytelling-img-caption1" %></p>
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124787/website/CP_logo_explanation.png" alt="CryptoPassion logo explanation" class="works-img">
        <p class="ui-regular-03 caption pt-2"><%= t "pages.cryptopassion.storytelling-img-caption2" %></p>
      </div>
      <div class="col-md-4 col-sm-12">
        <h2 class="sub-heading-03 mb-3"><%= t "pages.cryptopassion.storytelling-title" %></h2>
        <p class="ui-regular-01"><%= t "pages.cryptopassion.storytelling-description" %></p>
      </div>
    </div>
  </div>
</div>

<!-- Next project -->

<div class="next-work">
  <div class="container">
    <div class="d-md-flex justify-content-between mb-4">
      <h2 class="sub-heading-02 mb-3"><%= t "pages.works.next-work" %></h2>
    </div>

    <a href="<%= accor_path %>" style="text-decoration: none">
      <div class="next-work-section" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url(https://res.cloudinary.com/peachux/image/upload/v1669718549/website/Accor_next.png);">
        Accor
      </div>
    </a>
  </div>
</div>

<%= render "shared/advantages-block" %>

app/views/works/index.html.erb
<div class="works">
<h1 class="justify-content-center"><%= t "pages.works.title" %></h1>
  <div class="container">
    <div class="row justify-content-center">
      <a href="<%= accor_path %>" class="col-md-4 col-sm-12 work-card d-flex align-items-end p-4" style="background-image: url(https://res.cloudinary.com/peachux/image/upload/v1669124778/website/Accor_cover.jpg)">
        <h2 class="work-card-link">Accor</h2>
      </a>
      <a href="<%= kraze_path %>" class="col-md-4 col-sm-12 work-card d-flex align-items-end p-4" style="background-image: url(https://res.cloudinary.com/peachux/image/upload/v1669124771/website/Kraze_cover.jpg)">
        <h2 class="work-card-link">Kraze</h2>
      </a>
      <a href="<%= lcl_path %>" class="col-md-4 col-sm-12 work-card d-flex align-items-end p-4" style="background-image: url(https://res.cloudinary.com/peachux/image/upload/v1669124803/website/Lcl_cover.jpg)">
        <h2 class="work-card-link">LCL</h2>
      </a>
      <a href="<%= cryptopassion_path %>" class="col-md-4 col-sm-12 work-card d-flex align-items-end p-4" style="background-image: url(https://res.cloudinary.com/peachux/image/upload/v1669124787/website/CP_cover.jpg)">
        <h2 class="work-card-link">CryptoPassion</h2>
      </a>
    </div>
  </div>
  <%= render "shared/advantages-block" %>
</div>

app/views/works/kraze.html.erb
<!-- WORK HEADER -->

<div class="container">

  <%= render "shared/back-button" %>

  <div class="work-header d-flex">
    <div class="row align-self-stretch">
      <div class="col-md-7 col-sm-12 offset-md-0">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124771/website/Kraze_cover.jpg" alt="Kraze cover" class="work-header-image">
      </div>
      <div class="col-md-5 col-sm-12 work-header-content d-flex align-content-end flex-wrap offset-md-0 ps-4" >
        <h1 class="heading-02">Kraze</h1>
        <p class="ui-regular-01"><%= t "pages.kraze.description" %></p>
      </div>
    </div>
  </div>

<!-- GOALS -->

  <div class="work-block">
    <div class="row justify-content-center">
      <div class="col-md-4 col-sm-12">
        <h2 class="sub-heading-03 mb-3"><%= t "pages.kraze.goals-title" %></h2>
        <p class="ui-regular-01"><%= t "pages.kraze.goals-description_html" %></p>
      </div>
      <div class="col-md-4 col-sm-12">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124770/website/Kraze_goals.jpg" alt="Kraze goals" class="works-img">
        <p class="ui-regular-03 caption pt-2"><%= t "pages.kraze.goals-img-caption" %></p>
      </div>
    </div>
  </div>

<!-- INFORMATION ARCHITECTURE -->

  <div class="work-block">
    <div class="row justify-content-center">
      <div class="col-md-4 col-sm-12">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124770/website/Kraze_workshop.png" alt="Kraze info archi 1" class="works-img">
        <p class="ui-regular-03 caption pt-2"><%= t "pages.kraze.architecture-img-caption1" %></p>
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124769/website/Kraze_architecture.png" alt="Kraze info archi 2" class="works-img">
        <p class="ui-regular-03 caption pt-2"><%= t "pages.kraze.architecture-img-caption2" %></p>
      </div>
      <div class="col-md-4 col-sm-12">
        <h2 class="sub-heading-03 mb-3"><%= t "pages.kraze.architecture-title" %></h2>
        <p class="ui-regular-01"><%= t "pages.kraze.architecture-description" %></p>
      </div>
    </div>
  </div>
</div>

<!-- FOCUS -->

<div class="focus">
  <div class="container">
    <h2 class="sub-heading-03 text-center my-4"><%= t "pages.kraze.focus-title" %></h2>
    <div class="row justify-content-center">
      <div class="col-md-4 col-sm-12">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124770/website/Kraze_home.png" alt="Kraze home" class="kraze-screen">
        <p class="ui-regular-01 mt-3" style="color: white"><%= t "pages.kraze.focus-home" %></p>
      </div>
      <div class="col-md-4 col-sm-12">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124769/website/Kraze_feed.png" alt="Kraze post" class="kraze-screen">
        <p class="ui-regular-01 mt-3" style="color: white"><%= t "pages.kraze.focus-post" %></p>
      </div>
      <div class="col-md-4 col-sm-12">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124770/website/Kraze_event.png" alt="Kraze event" class="kraze-screen">
        <p class="ui-regular-01 mt-3" style="color: white"><%= t "pages.kraze.focus-event" %></p>
      </div>
    </div>
  </div>
</div>

<!-- Design system and library -->

<div class="container">
  <div class="work-block">
    <div class="row justify-content-center">
      <div class="col-md-4 col-sm-12">
        <h2 class="sub-heading-03 mb-3"><%= t "pages.kraze.ds-title" %></h2>
        <p class="ui-regular-01"><%= t "pages.kraze.ds-description" %></p>
      </div>
      <div class="col-md-4 col-sm-12">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669124770/website/Kraze_library.png" alt="Kraze DS" class="works-img">
        <p class="ui-regular-03 caption pt-2"><%= t "pages.kraze.ds-img-caption" %></p>
      </div>
    </div>
  </div>

<!-- Design system and library -->

  <div class="work-block">
    <div class="row justify-content-center">
      <div class="col-md-4 col-sm-12">
        <img src="https://res.cloudinary.com/peachux/image/upload/v1669717429/website/Kraze_prototyping.png" alt="Kraze prototype" class="works-img">
        <p class="ui-regular-03 caption pt-2"><%= t "pages.kraze.proto-img-caption" %></p>
      </div>
      <div class="col-md-4 col-sm-12">
        <h2 class="sub-heading-03 mb-3"><%= t "pages.kraze.proto-title" %></h2>
        <p class="ui-regular-01"><%= t "pages.kraze.proto-description" %></p>
      </div>
    </div>
  </div>
</div>

<!-- Next project -->

<div class="next-work">
  <div class="container">
    <div class="d-md-flex justify-content-between mb-4">
      <h2 class="sub-heading-02 mb-3"><%= t "pages.works.next-work" %></h2>
    </div>

    <a href="<%= lcl_path %>" style="text-decoration: none">
      <div class="next-work-section" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url(https://res.cloudinary.com/peachux/image/upload/v1669718527/website/Lcl_next.png);">
        LCL
      </div>
    </a>
  </div>
</div>

<%= render "shared/advantages-block" %>